using System;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEngine;
using YooAsset.Editor;

namespace CensorPort.Editor
{
    /// <summary>
    /// Writes Assets/Resources/CensorPackageIndex.txt from the REAL buildin output of every
    /// package that has one.
    ///
    /// Why shared: the index is what AssetsManager reads to decide whether the optional
    /// DLCPackage exists (PackageIndex.Validate requires manifestFileName/manifestSize/
    /// manifestSha256 for every included package, and a broken index makes the player throw
    /// "Package index is unusable").  Both build entry points must therefore produce the same
    /// answer; a hardcoded "DLCPackage included=false" in the RootPackage-only builder would
    /// silently switch the DLC off again on the next root bundle build.
    ///
    /// ASCII-only on purpose.
    /// </summary>
    public static class PortPackageIndex
    {
        public const string RootPackageName = "RootPackage";
        public const string DlcPackageName = "DLCPackage";
        public const string PackageVersion = "1.0";

        public static void Write(StringBuilder sb)
        {
            sb.AppendLine();
            sb.AppendLine("--- package index from the real output ---");
            string buildinRoot = AssetBundleBuilderHelper.GetStreamingAssetsRoot();

            string rootJson = Entry(buildinRoot, RootPackageName, true, true, sb);
            string dlcJson = Entry(buildinRoot, DlcPackageName, false, false, sb);

            string json =
                "{\n" +
                "  \"generatedAt\": \"" + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") + "\",\n" +
                "  \"buildTarget\": \"Android\",\n" +
                "  \"yooFolder\": \"dynamic_assets\",\n" +
                "  \"note\": \"Generated by the port build scripts from the real Android bundle output. Do not hand-edit.\",\n" +
                "  \"packages\": [\n" +
                rootJson + ",\n" +
                dlcJson + "\n" +
                "  ]\n" +
                "}\n";

            string indexPath = "Assets/Resources/CensorPackageIndex.txt";
            File.WriteAllText(indexPath, json, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(indexPath, ImportAssetOptions.ForceUpdate);
            sb.AppendLine("  wrote " + indexPath);
            foreach (string l in json.Split('\n')) sb.AppendLine("     " + l.TrimEnd());
        }

        /// <summary>
        /// One index entry.  `included` is derived from whether a real manifest was found, so an
        /// unbuilt package is honestly reported as absent and a built one carries real metadata.
        /// </summary>
        private static string Entry(string buildinRoot, string packageName, bool required,
                                    bool mustExist, StringBuilder sb)
        {
            string dir = buildinRoot + packageName + "/";
            sb.AppendLine("  package " + packageName + " : buildin dir = " + dir);
            string manifestFile = null;
            if (Directory.Exists(dir))
                manifestFile = Directory.GetFiles(dir, "PackageManifest_" + packageName + "_*.bytes")
                                        .OrderByDescending(f => f).FirstOrDefault();

            if (manifestFile == null)
            {
                if (mustExist)
                    sb.AppendLine("    !! MISSING manifest -- the buildin copy step did not run");
                else
                    sb.AppendLine("    no manifest (package not built) -> reported as included=false");
                return EntryJson(packageName, string.Empty, 0, 0, string.Empty, 0, 0, required, false);
            }

            string[] bundles = Directory.GetFiles(dir, "*.bundle");
            long bundleBytes = bundles.Sum(b => new FileInfo(b).Length);
            string sha = Sha256(manifestFile);
            long msize = new FileInfo(manifestFile).Length;
            sb.AppendLine("    manifestFileName = " + Path.GetFileName(manifestFile));
            sb.AppendLine("    manifestSize     = " + msize);
            sb.AppendLine("    manifestSha256   = " + sha);
            sb.AppendLine("    bundleCount      = " + bundles.Length);
            sb.AppendLine("    bundleTotalBytes = " + bundleBytes);
            return EntryJson(packageName, Path.GetFileName(manifestFile), msize, bundleBytes, sha,
                             bundles.Length, bundleBytes, required, true);
        }

        private static string EntryJson(string name, string manifestFileName, long manifestSize,
                                        long bundleTotalBytes, string sha, int bundleCount,
                                        long unused, bool required, bool included)
        {
            return
                "    {\n" +
                "      \"name\": \"" + name + "\",\n" +
                "      \"version\": \"" + PackageVersion + "\",\n" +
                "      \"required\": " + (required ? "true" : "false") + ",\n" +
                "      \"included\": " + (included ? "true" : "false") + ",\n" +
                "      \"manifestFileName\": \"" + manifestFileName + "\",\n" +
                "      \"manifestSize\": " + manifestSize + ",\n" +
                "      \"manifestSha256\": \"" + sha + "\",\n" +
                "      \"bundleCount\": " + bundleCount + ",\n" +
                "      \"bundleTotalBytes\": " + bundleTotalBytes + "\n" +
                "    }";
        }

        private static string Sha256(string path)
        {
            using (var sha = SHA256.Create())
            using (var s = File.OpenRead(path))
                return string.Concat(sha.ComputeHash(s).Select(b => b.ToString("x2")));
        }
    }
}
